/**
 * Markdown renderer for the Intent Document.
 *
 * The zero-install fallback: rendered into the PR description (by the MCP server) and
 * the guided-review comment, so the document has value even without the viewer.
 */

import type { IntentDocument } from "@review-assist/schema";

export interface RenderOptions {
  /** If provided, appends an "Open guided review →" link. */
  viewerUrl?: string;
}

/** Render the optional Mermaid diagrams as fenced blocks (GitHub renders these natively). */
function diagramsMarkdown(doc: IntentDocument): string[] {
  const out: string[] = [];
  if (!doc.diagrams?.length) return out;
  out.push(`### 📊 Diagrams`, ``);
  for (const d of doc.diagrams) {
    out.push(`**${escape(d.title)}**`, ``);
    out.push("```mermaid", d.mermaid.trim(), "```", ``); // never flatten: mermaid is multi-line
    if (d.caption) out.push(`_${escape(d.caption)}_`, ``);
  }
  return out;
}

export function renderMarkdown(doc: IntentDocument, opts: RenderOptions = {}): string {
  const out: string[] = [];
  const p = (s = "") => out.push(s);

  p(`## 🧭 Intent Document`);
  p();
  p(`> ${escape(doc.problem.statement)}`);
  p();

  if (opts.viewerUrl) {
    p(`**[Open guided review →](${opts.viewerUrl})**`);
    p();
  }

  // Assumptions — the front page.
  if (doc.assumptions.length) {
    p(`### ⚠️ Assumptions — review these first`);
    p();
    p(`If any of these is wrong, the change likely needs rework regardless of line-by-line review.`);
    p();
    for (const a of doc.assumptions) {
      p(`- **[${a.id}] ${escape(a.assumption)}** _(${labelConfidence(a.confidence)})_`);
      p(`  - If wrong: ${escape(a.impact_if_wrong)}`);
      if (a.how_to_verify) p(`  - Verify by: ${escape(a.how_to_verify)}`);
    }
    p();
  }

  if (doc.open_questions?.length) {
    p(`### ❓ Open questions`);
    p();
    for (const q of doc.open_questions) {
      p(`- **[${q.id}]** ${escape(q.question)}`);
      if (q.context) p(`  - ${escape(q.context)}`);
    }
    p();
  }

  // Problem detail.
  if (doc.problem.out_of_scope?.length) {
    p(`**Out of scope:** ${doc.problem.out_of_scope.map(escape).join("; ")}`);
    p();
  }

  // Approach.
  p(`### 🛠 Approach`);
  p();
  for (const line of blockMarkdown("", doc.approach.adopted.summary)) p(line);
  for (const line of blockMarkdown("_Why:_ ", doc.approach.adopted.rationale)) p(line);
  if (doc.approach.requirements?.length) {
    p(`**Requirements**`);
    p();
    for (const r of doc.approach.requirements) {
      p(`- ${escape(r.text)}${r.source ? ` — _${escape(r.source)}_` : ""}`);
    }
    p();
  }
  if (doc.approach.trials?.length) {
    p(`**Considered and rejected**`);
    p();
    for (const t of doc.approach.trials) {
      p(`- **Tried:** ${escape(t.what)}`);
      p(`  - **Outcome:** ${escape(t.outcome)}`);
      p(`  - **Abandoned because:** ${escape(t.why_abandoned)}`);
    }
    p();
  }

  for (const line of diagramsMarkdown(doc)) p(line);

  // Guided tour.
  p(`### 🚶 Guided tour`);
  p();
  for (const stop of orderTour(doc.tour)) {
    const badge = stop.role === "incidental" ? " _(incidental)_" : stop.role === "supporting" ? " _(supporting)_" : "";
    p(`#### ${stop.id}. ${escape(stop.title)}${badge}`);
    for (const line of fieldMarkdown("What", stop.what)) p(line);
    for (const line of fieldMarkdown("Why", stop.why)) p(line);
    if (stop.attention) p(`- **👀 Look here:** ${escape(stop.attention)}`);
    const files = [...new Set(stop.anchors.map((a) => a.path))];
    if (files.length) p(`- **Files:** ${files.map((f) => `\`${f}\``).join(", ")}`);
    p();
  }

  // Verification.
  p(`### ✅ Verification`);
  p();
  for (const v of doc.verification.performed) {
    p(`- ${resultIcon(v.result)} **${v.kind}:** ${escape(v.description)} — ${escape(v.result)}`);
  }
  if (doc.verification.not_verified?.length) {
    p();
    p(`**Not verified:**`);
    for (const n of doc.verification.not_verified) p(`- ⚠️ ${escape(n)}`);
  }
  p();

  p(`<sub>Generated by ${escape(doc.meta.generated_by.pipeline)} v${escape(doc.meta.generated_by.version)} from session on \`${doc.meta.commit_range.head_sha.slice(0, 7)}\`. Schema ${doc.schema_version}.</sub>`);

  return out.join("\n");
}

/**
 * A concise PR description rendered from the Intent Document: problem, approach,
 * what was considered and rejected, any diagrams, and the assumptions to check
 * first. The full guided tour lives in the viewer / webhook comment, not the PR body.
 *
 * Rejected alternatives are here rather than behind a fold because they are the one
 * thing a diff-only reviewer cannot reconstruct, and the PR body is the surface that
 * actually gets read.
 */
export function renderPrDescription(doc: IntentDocument, opts: RenderOptions = {}): string {
  const out: string[] = [];
  const p = (s = "") => out.push(s);

  p(`## ${escape(doc.problem.statement)}`);
  p();
  for (const line of blockMarkdown("**What changed.** ", doc.approach.adopted.summary)) p(line);
  for (const line of blockMarkdown("_Why:_ ", doc.approach.adopted.rationale)) p(line);

  for (const line of diagramsMarkdown(doc)) p(line);

  if (doc.assumptions.length) {
    p(`### Assumptions to check first`);
    p();
    for (const a of doc.assumptions) {
      const v = a.how_to_verify ? ` _Verify:_ ${escape(a.how_to_verify)}` : "";
      p(`- **[${a.id}] ${escape(a.assumption)}** — if wrong: ${escape(a.impact_if_wrong)}.${v}`);
    }
    p();
  }

  if (doc.approach.trials?.length) {
    p(`### Considered and rejected`);
    p();
    for (const t of doc.approach.trials) {
      p(`- **${escape(t.what)}** — ${escape(t.why_abandoned)}`);
    }
    p();
  }

  if (doc.problem.out_of_scope?.length) {
    p(`**Out of scope:** ${doc.problem.out_of_scope.map(escape).join("; ")}`);
    p();
  }

  const link = opts.viewerUrl ? `[Open the guided review →](${opts.viewerUrl}) · ` : "";
  p(`---`);
  p(`<sub>🧭 ${link}Intent captured by Review Assist. A guided walkthrough is linked on this PR automatically; full detail lives in the committed Intent Document.</sub>`);

  return out.join("\n");
}

/** Order tour stops depth-first following parent links, preserving array order among siblings. */
export function orderTour<T extends { id: string; parent?: string | null }>(tour: T[]): T[] {
  const byParent = new Map<string | null, T[]>();
  for (const stop of tour) {
    const key = stop.parent ?? null;
    if (!byParent.has(key)) byParent.set(key, []);
    byParent.get(key)!.push(stop);
  }
  const known = new Set(tour.map((t) => t.id));
  const result: T[] = [];
  const visit = (parent: string | null) => {
    for (const stop of byParent.get(parent) ?? []) {
      result.push(stop);
      visit(stop.id);
    }
  };
  visit(null);
  // Any stop whose parent isn't null and isn't a known id (shouldn't happen post-validation)
  // gets appended so nothing is silently dropped.
  for (const stop of tour) {
    if (!result.includes(stop) && stop.parent != null && !known.has(stop.parent)) {
      result.push(stop);
    }
  }
  return result;
}

function labelConfidence(c: string): string {
  switch (c) {
    case "confirmed_by_user": return "confirmed by user";
    case "grounded_in_code": return "grounded in code";
    default: return "unverified";
  }
}

function resultIcon(result: string): string {
  return /pass|ok|success/i.test(result) ? "✅" : /fail|error/i.test(result) ? "❌" : "•";
}

function escape(s: string): string {
  return s.replace(/\r?\n/g, " ");
}

/**
 * A tour stop's `what` is authored as a bulleted list of behaviour changes, so it is the
 * one field that must not be flattened: `escape` would run every bullet into a single
 * paragraph, which is the prose form the field was rewritten to stop producing.
 *
 * Nested under the label rather than replacing it, so the stop keeps its What/Why/Look
 * here shape. A `what` that is one line — or several lines with no bullet among them —
 * still renders inline, because indenting a lone fragment under an empty label reads as
 * a rendering fault rather than a list.
 */
const isBullet = (l: string) => /^[-*+]\s+/.test(l.trim());

/** Split a point-list field into lines; a single unbulleted value stays one line. */
function pointLines(text: string): string[] | null {
  const lines = text.split(/\r?\n/).filter((l) => l.trim().length > 0);
  if (lines.length <= 1 || !lines.some(isBullet)) return null;
  return lines;
}

/**
 * A labelled field, nested under a parent bullet. Every document field is a list of
 * points now, so a field rendered as one string collapses its newlines and shows the
 * dashes inline — which is what a reader sees instead of a list.
 */
function fieldMarkdown(label: string, text: string): string[] {
  const lines = pointLines(text);
  if (!lines) return [`- **${label}:** ${escape(text)}`];
  return [
    `- **${label}:**`,
    ...lines.map((l) => {
      const t = l.trim();
      // Two spaces indents a bullet under the label; four continues the bullet above it.
      return isBullet(t) ? `  - ${t.replace(/^[-*+]\s+/, "")}` : `    ${t}`;
    }),
  ];
}

/** A top-level field: bullets must start on their own line or the list does not form. */
function blockMarkdown(lead: string, text: string): string[] {
  const lines = pointLines(text);
  if (!lines) return [`${lead}${escape(text)}`, ``];
  return [lead.trim(), ``, ...lines.map((l) => (isBullet(l.trim()) ? `- ${l.trim().replace(/^[-*+]\s+/, "")}` : l.trim())), ``];
}
