/**
 * Markdown renderer for the Intent Document.
 *
 * This is the zero-install fallback: the GitHub Action posts this as a PR comment
 * so the document has value even for reviewers who never open the guided viewer.
 */

import type { IntentDocument } from "@review-assist/schema";

export interface RenderOptions {
  /** If provided, appends an "Open guided review →" link. */
  viewerUrl?: string;
}

export function renderMarkdown(doc: IntentDocument, opts: RenderOptions = {}): string {
  const out: string[] = [];
  const p = (s = "") => out.push(s);

  p(`## 🧭 Intent Document`);
  p();
  p(`> ${escape(doc.problem.statement)}`);
  p();

  if (opts.viewerUrl) {
    p(`**[Open guided review →](${opts.viewerUrl})**`);
    p();
  }

  // Assumptions — the front page.
  if (doc.assumptions.length) {
    p(`### ⚠️ Assumptions — review these first`);
    p();
    p(`If any of these is wrong, the change likely needs rework regardless of line-by-line review.`);
    p();
    for (const a of doc.assumptions) {
      p(`- **[${a.id}] ${escape(a.assumption)}** _(${labelConfidence(a.confidence)})_`);
      p(`  - If wrong: ${escape(a.impact_if_wrong)}`);
      if (a.how_to_verify) p(`  - Verify by: ${escape(a.how_to_verify)}`);
    }
    p();
  }

  if (doc.open_questions?.length) {
    p(`### ❓ Open questions`);
    p();
    for (const q of doc.open_questions) {
      p(`- **[${q.id}]** ${escape(q.question)}`);
      if (q.context) p(`  - ${escape(q.context)}`);
    }
    p();
  }

  // Problem detail.
  if (doc.problem.origin === "emerged_during_session" && doc.problem.evolution?.length) {
    p(`### 🎯 How the ask evolved`);
    p();
    for (const e of doc.problem.evolution) {
      p(`- _${escape(e.at)}_: ${escape(e.formulation)}`);
    }
    p();
  }
  if (doc.problem.out_of_scope?.length) {
    p(`**Out of scope:** ${doc.problem.out_of_scope.map(escape).join("; ")}`);
    p();
  }

  // Approach.
  p(`### 🛠 Approach`);
  p();
  p(escape(doc.approach.adopted.summary));
  p();
  p(`_Why:_ ${escape(doc.approach.adopted.rationale)}`);
  p();
  if (doc.approach.trials?.length) {
    p(`<details><summary>Rejected alternatives (${doc.approach.trials.length})</summary>`);
    p();
    for (const t of doc.approach.trials) {
      p(`- **Tried:** ${escape(t.what)}`);
      p(`  - **Outcome:** ${escape(t.outcome)}`);
      p(`  - **Abandoned because:** ${escape(t.why_abandoned)}`);
    }
    p();
    p(`</details>`);
    p();
  }

  // Guided tour.
  p(`### 🚶 Guided tour`);
  p();
  for (const stop of orderTour(doc.tour)) {
    const badge = stop.role === "incidental" ? " _(incidental)_" : stop.role === "supporting" ? " _(supporting)_" : "";
    p(`#### ${stop.id}. ${escape(stop.title)}${badge}`);
    p(`- **What:** ${escape(stop.what)}`);
    p(`- **Why:** ${escape(stop.why)}`);
    if (stop.attention) p(`- **👀 Look here:** ${escape(stop.attention)}`);
    const files = [...new Set(stop.anchors.map((a) => a.path))];
    if (files.length) p(`- **Files:** ${files.map((f) => `\`${f}\``).join(", ")}`);
    p();
  }

  // Verification.
  p(`### ✅ Verification`);
  p();
  for (const v of doc.verification.performed) {
    p(`- ${resultIcon(v.result)} **${v.kind}:** ${escape(v.description)} — ${escape(v.result)}`);
  }
  if (doc.verification.not_verified?.length) {
    p();
    p(`**Not verified:**`);
    for (const n of doc.verification.not_verified) p(`- ⚠️ ${escape(n)}`);
  }
  p();

  p(`<sub>Generated by ${escape(doc.meta.generated_by.pipeline)} v${escape(doc.meta.generated_by.version)} from session on \`${doc.meta.commit_range.head_sha.slice(0, 7)}\`. Schema ${doc.schema_version}.</sub>`);

  return out.join("\n");
}

/** Order tour stops depth-first following parent links, preserving array order among siblings. */
export function orderTour<T extends { id: string; parent?: string | null }>(tour: T[]): T[] {
  const byParent = new Map<string | null, T[]>();
  for (const stop of tour) {
    const key = stop.parent ?? null;
    if (!byParent.has(key)) byParent.set(key, []);
    byParent.get(key)!.push(stop);
  }
  const known = new Set(tour.map((t) => t.id));
  const result: T[] = [];
  const visit = (parent: string | null) => {
    for (const stop of byParent.get(parent) ?? []) {
      result.push(stop);
      visit(stop.id);
    }
  };
  visit(null);
  // Any stop whose parent isn't null and isn't a known id (shouldn't happen post-validation)
  // gets appended so nothing is silently dropped.
  for (const stop of tour) {
    if (!result.includes(stop) && stop.parent != null && !known.has(stop.parent)) {
      result.push(stop);
    }
  }
  return result;
}

function labelConfidence(c: string): string {
  switch (c) {
    case "confirmed_by_user": return "confirmed by user";
    case "grounded_in_code": return "grounded in code";
    default: return "unverified";
  }
}

function resultIcon(result: string): string {
  return /pass|ok|success/i.test(result) ? "✅" : /fail|error/i.test(result) ? "❌" : "•";
}

function escape(s: string): string {
  return s.replace(/\r?\n/g, " ");
}
